# Generated by Django 5.0 on 2025-11-30 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="请输入武器名称",
                        max_length=100,
                        verbose_name="武器名称",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="上传 PNG/JPG 格式图片",
                        upload_to="weapons/%Y/%m/%d/",
                        verbose_name="武器图片",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="请输入武器详细描述", verbose_name="描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "owner_character",
                    models.ForeignKey(
                        help_text="选择武器拥有者角色",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weapons",
                        to="create.character",
                        verbose_name="拥有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "武器",
                "verbose_name_plural": "武器列表",
                "ordering": ["-created_at"],
            },
        ),
    ]
