# Generated by Django 5.0 on 2025-11-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0002_weapon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weapon",
            name="owner_character",
        ),
        migrations.DeleteModel(
            name="Character",
        ),
        migrations.DeleteModel(
            name="Weapon",
        ),
    ]
