# Generated by Django 5.0 on 2025-11-30 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("create", "0003_remove_weapon_owner_character_delete_character_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="请输入角色名称",
                        max_length=100,
                        verbose_name="人物名称",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="上传 PNG/JPG 格式图片",
                        upload_to="characters/%Y/%m/%d/",
                        verbose_name="人物图片",
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[("人", "人"), ("妖", "妖"), ("仙", "仙")],
                        help_text="请选择人/妖/仙族",
                        max_length=10,
                        verbose_name="种族",
                    ),
                ),
                (
                    "ability",
                    models.CharField(
                        help_text="请输入角色能力描述",
                        max_length=200,
                        verbose_name="能力",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        help_text="请输入角色详细介绍", verbose_name="介绍"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色列表",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="请输入武器名称",
                        max_length=100,
                        verbose_name="武器名称",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="上传 PNG/JPG 格式图片",
                        upload_to="weapons/%Y/%m/%d/",
                        verbose_name="武器图片",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="请输入武器详细描述", verbose_name="描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "owner_character",
                    models.ForeignKey(
                        help_text="选择武器拥有者角色",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weapons",
                        to="create.character",
                        verbose_name="拥有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "武器",
                "verbose_name_plural": "武器列表",
                "ordering": ["-created_at"],
            },
        ),
    ]
