# Generated by Django 5.0 on 2025-11-30 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="请输入大陆名称",
                        max_length=100,
                        unique=True,
                        verbose_name="大陆名称",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "大陆",
                "verbose_name_plural": "大陆列表",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="character",
            name="organization",
            field=models.CharField(
                default="无组织",
                help_text="请输入组织名称",
                max_length=100,
                verbose_name="组织名称",
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="owner_character",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="选择武器拥有者角色",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weapons",
                to="create.character",
                verbose_name="拥有者",
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="请输入地点名称",
                        max_length=100,
                        verbose_name="地点名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="请输入地点详细描述", verbose_name="描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "continent_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="选择地点所属大陆",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="create.continent",
                        verbose_name="所属大陆",
                    ),
                ),
            ],
            options={
                "verbose_name": "地点",
                "verbose_name_plural": "地点列表",
                "ordering": ["-created_at"],
            },
        ),
    ]
