# Generated by Django 5.0 on 2025-11-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0005_continent_character_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relationship_Type",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="关系id"
                    ),
                ),
                ("type", models.CharField(max_length=100, verbose_name="关系名")),
                ("description", models.TextField(verbose_name="描述")),
            ],
            options={
                "verbose_name": "关系类型",
                "verbose_name_plural": "关系类型",
                "db_table": "relationship_type",
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "chapter_number",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="回合号"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="回目标题")),
                ("summary", models.TextField(verbose_name="大致内容")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="create.location",
                        verbose_name="地点编号",
                    ),
                ),
            ],
            options={
                "verbose_name": "章节",
                "verbose_name_plural": "章节",
                "db_table": "chapter",
            },
        ),
        migrations.CreateModel(
            name="Calamity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="磨难编号"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("summary", models.TextField(verbose_name="大致内容")),
                (
                    "chapter_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="create.chapter",
                        verbose_name="关联到磨难发生的章节",
                    ),
                ),
            ],
            options={
                "verbose_name": "磨难",
                "verbose_name_plural": "磨难",
                "db_table": "calamity",
            },
        ),
        migrations.CreateModel(
            name="Character_Relationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="关系 ID"
                    ),
                ),
                (
                    "from_character_id",
                    models.ForeignKey(
                        help_text="关系发起方（from_person_id）",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_relationships",
                        to="create.character",
                        verbose_name="发起方角色 ID",
                    ),
                ),
                (
                    "to_character_id",
                    models.ForeignKey(
                        help_text="关系接收方（to_person_id）",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_relationships",
                        to="create.character",
                        verbose_name="接收方角色 ID",
                    ),
                ),
                (
                    "relationship_type_id",
                    models.ForeignKey(
                        help_text="关系类型",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="create.relationship_type",
                        verbose_name="关系类型 ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "人物关系",
                "verbose_name_plural": "人物关系列表",
            },
        ),
        migrations.CreateModel(
            name="Chapter_Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapter_number",
                    models.ForeignKey(
                        help_text="关联章节编号",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="create.chapter",
                        verbose_name="章节编号",
                    ),
                ),
                (
                    "character_id",
                    models.ForeignKey(
                        help_text="关联角色编号",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="create.character",
                        verbose_name="角色编号",
                    ),
                ),
                (
                    "place_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="事件发生地点（可选）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="create.location",
                        verbose_name="事件发生地点",
                    ),
                ),
            ],
            options={
                "verbose_name": "章节-人物关联",
                "verbose_name_plural": "章节-人物关联列表",
                "ordering": ["chapter_number", "character_id"],
                "unique_together": {("chapter_number", "character_id")},
            },
        ),
    ]
