# Generated by Django 5.0 on 2025-11-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0006_relationship_type_chapter_calamity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="continent",
            name="description",
            field=models.CharField(
                blank=True, help_text="请输入描述", max_length=200, verbose_name="描述"
            ),
        ),
    ]
