# Generated by Django 5.0 on 2025-11-30 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0007_continent_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calamity",
            name="chapter_number",
        ),
        migrations.AddField(
            model_name="chapter",
            name="calamity_id",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="create.calamity",
            ),
        ),
    ]
