# Generated by Django 5.0 on 2025-11-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0008_remove_calamity_chapter_number_chapter_calamity_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="calamity_id",
            new_name="calamity",
        ),
        migrations.RenameField(
            model_name="chapter_character",
            old_name="character_id",
            new_name="character",
        ),
        migrations.RenameField(
            model_name="chapter_character",
            old_name="place_id",
            new_name="place",
        ),
        migrations.RenameField(
            model_name="character_relationship",
            old_name="relationship_type_id",
            new_name="relationship_type",
        ),
        migrations.RenameField(
            model_name="character_relationship",
            old_name="to_character_id",
            new_name="to_character",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="continent_id",
            new_name="continent",
        ),
    ]
