# Generated by Django 5.0 on 2025-11-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0009_rename_calamity_id_chapter_calamity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter_character",
            options={
                "ordering": ["chapter_number", "character"],
                "verbose_name": "章节-人物关联",
                "verbose_name_plural": "章节-人物关联列表",
            },
        ),
        migrations.AlterField(
            model_name="calamity",
            name="id",
            field=models.IntegerField(
                default=82, primary_key=True, serialize=False, verbose_name="磨难编号"
            ),
        ),
    ]
