# Generated by Django 5.0 on 2025-11-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0010_alter_chapter_character_options_alter_calamity_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="continent",
            name="id",
            field=models.IntegerField(
                default=5, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
