# Generated by Django 5.0 on 2025-11-30 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0011_alter_continent_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="calamity",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="location",
        ),
        migrations.AlterField(
            model_name="chapter_character",
            name="place",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="事件发生地点（可选）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="create.location",
                verbose_name="事件发生地点",
            ),
        ),
        migrations.CreateModel(
            name="Chapter_Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="create.chapter"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="create.location",
                    ),
                ),
            ],
        ),
    ]
