# Generated by Django 5.0 on 2025-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0012_remove_chapter_calamity_remove_chapter_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="description",
            field=models.TextField(
                default="暂无", help_text="请输入地点详细描述", verbose_name="描述"
            ),
        ),
    ]
