# Generated by Django 5.0 on 2025-11-30 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0013_alter_location_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter_location",
            options={
                "ordering": ["chapter__chapter_number", "location__name"],
                "verbose_name": "章节地点关联",
                "verbose_name_plural": "章节地点关联列表",
            },
        ),
        migrations.AlterField(
            model_name="chapter_location",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_locations",
                to="create.chapter",
                verbose_name="章节",
            ),
        ),
        migrations.AlterField(
            model_name="chapter_location",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_locations",
                to="create.location",
                verbose_name="地点",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chapter_location",
            unique_together={("chapter", "location")},
        ),
        migrations.AlterModelTable(
            name="chapter_location",
            table="chapter_location",
        ),
    ]
