# Generated by Django 5.0 on 2025-12-01 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0014_alter_chapter_location_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character_relationship",
            name="from_character_id",
        ),
        migrations.RemoveField(
            model_name="character_relationship",
            name="to_character",
        ),
        migrations.AddField(
            model_name="character_relationship",
            name="subordinate",
            field=models.ForeignKey(
                default=0,
                help_text="关系接收方（to_person_id）",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_relationships",
                to="create.character",
                verbose_name="Subordinate ID",
            ),
        ),
        migrations.AddField(
            model_name="character_relationship",
            name="superior",
            field=models.ForeignKey(
                default=0,
                help_text="关系发起方（from_person_id）",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_relationships",
                to="create.character",
                verbose_name="Superiors ID",
            ),
        ),
    ]
