# Generated by Django 5.0 on 2025-12-01 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0015_remove_character_relationship_from_character_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character_relationship",
            name="subordinate",
            field=models.ForeignKey(
                default=None,
                help_text="关系接收方（to_person_id）",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_relationships",
                to="create.character",
                verbose_name="Subordinate ID",
            ),
        ),
        migrations.AlterField(
            model_name="character_relationship",
            name="superior",
            field=models.ForeignKey(
                default=None,
                help_text="关系发起方（from_person_id）",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_relationships",
                to="create.character",
                verbose_name="Superiors ID",
            ),
        ),
    ]
