# Generated by Django 5.0 on 2025-12-01 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0016_alter_character_relationship_subordinate_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Character_Relationship",
        ),
    ]
