# Generated by Django 5.0 on 2025-12-01 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0017_delete_character_relationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character_Relationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="关系 ID"
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        help_text="关系类型",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="create.relationship_type",
                        verbose_name="关系类型 ID",
                    ),
                ),
                (
                    "subordinate",
                    models.ForeignKey(
                        default=None,
                        help_text="关系接收方（to_person_id）",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_relationships",
                        to="create.character",
                        verbose_name="Subordinate ID",
                    ),
                ),
                (
                    "superior",
                    models.ForeignKey(
                        default=None,
                        help_text="关系发起方（from_person_id）",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_relationships",
                        to="create.character",
                        verbose_name="Superiors ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "人物关系",
                "verbose_name_plural": "人物关系列表",
            },
        ),
    ]
