# Generated by Django 5.0 on 2025-12-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0018_character_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship_type",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="描述"
            ),
        ),
    ]
