# Generated by Django 5.0 on 2025-12-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0019_alter_relationship_type_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="image",
            field=models.ImageField(
                default=None,
                help_text="上传 PNG/JPG 格式图片",
                upload_to="characters/%Y/%m/%d/",
                verbose_name="人物图片",
            ),
        ),
    ]
