# Generated by Django 5.0 on 2025-12-02 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0020_alter_character_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character_relationship",
            name="subordinate",
        ),
        migrations.RemoveField(
            model_name="character_relationship",
            name="superior",
        ),
        migrations.AddField(
            model_name="character_relationship",
            name="from_character",
            field=models.ForeignKey(
                default=None,
                help_text="关系发起方（from_person_id）",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_relationships",
                to="create.character",
                verbose_name="关系发起方 ID",
            ),
        ),
        migrations.AddField(
            model_name="character_relationship",
            name="to_character",
            field=models.ForeignKey(
                default=None,
                help_text="关系接收方（to_person_id）",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_relationships",
                to="create.character",
                verbose_name="关系接收方 ID",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="continent",
            field=models.ForeignKey(
                blank=True,
                help_text="选择地点所属大陆",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="create.continent",
                verbose_name="所属大陆",
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="owner_character",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="选择武器拥有者角色",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weapons",
                to="create.character",
                verbose_name="拥有者",
            ),
        ),
        migrations.DeleteModel(
            name="Chapter_Character",
        ),
    ]
